app:
  message: Message has been sent Successfully..
spring:
  rabbitmq:
    host: localhost
    password: guest
    port: 15672
    username: guest
    exchange: ecommerce.exchange
    queue: product.queue
    routingkey: product.routingkey
server:
  port: 9091